[package]
name = "game_of_life"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28"
winit_input_helper = "0.14"
pixels = "0.13.0"
rand = "*"
once_cell = "1.19.0"